[package]
name = "narou-epub"
version = "0.1.0"
edition = "2024"
description = "小説家になろうの作品を EPUB3 に変換するツール"
readme = "README.md"
license = "MIT"
authors = ["SaitoAtsushi <maldikulo@gmail.com>"]

[dependencies]
indicatif = "0.18.3"
minreq = { version = "2.14.1", features = ["https-native", "json-using-serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = { version = "1", default-features = false, features = ["std"] }
sanitize-filename = "0.6.0"
chrono = "0.4.42"
uuid = { version = "1", features = ["v5"] }
zip-builder = { git = "https://github.com/SaitoAtsushi/zip-builder.git", tag = "0.1" }

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
strip = "symbols"
